CREATE DATABASE DB_ECOMMERCE;

USE DB_ECOMMERCE;

CREATE TABLE TB_SHOP(

ID BIGINT AUTO_INCREMENT,
PRODUCT VARCHAR(255) NOT NULL,
PRICE DECIMAL (8, 2) NOT NULL,
DESCRICAO VARCHAR(255),
BRAND VARCHAR(255),
VALIDATE DOUBLE,
PRIMARY KEY(ID)

);

INSERT INTO TB_SHOP(PRODUCT, PRICE, DESCRICAO, BRAND, VALIDATE) VALUES ("Iphone 13 Pro", 3.600, "Celular de ultima geração", "Apple", 0);
INSERT INTO TB_SHOP(PRODUCT, PRICE, DESCRICAO, BRAND, VALIDATE) VALUES ("Camisa", 399.99, "Camisa masculina", "Nike", 0);
INSERT INTO TB_SHOP(PRODUCT, PRICE, DESCRICAO, BRAND, VALIDATE) VALUES ("Bone preto", 599.99, "Boné sport preto", "Lacoste", 0);
INSERT INTO TB_SHOP(PRODUCT, PRICE, DESCRICAO, BRAND, VALIDATE) VALUES ("Polo", 799.99, "Camisa polo branca", "Lacoste", 0);
INSERT INTO TB_SHOP(PRODUCT, PRICE, DESCRICAO, BRAND, VALIDATE) VALUES ("Chinelo", 299.99, "Chinelo branco com simbolo da bandeira brasileira", "Havaianas", 0);
INSERT INTO TB_SHOP(PRODUCT, PRICE, DESCRICAO, BRAND, VALIDATE) VALUES ("Air pods", 1.999, "Fones de ouvido sem fio", "Apple", 0);
INSERT INTO TB_SHOP(PRODUCT, PRICE, DESCRICAO, BRAND, VALIDATE) VALUES ("Teclado gamer", 499.99, "Teclado mecanico switch yellow", "GK", 0);
INSERT INTO TB_SHOP(PRODUCT, PRICE, DESCRICAO, BRAND, VALIDATE) VALUES ("Computador gamer", 9.999, "Computador gamer de ultima geração", "Variado", 0);

SELECT * FROM TB_SHOP WHERE PRICE < 500;

uptade TB_SHOP SET PRICE = 599.99 ID = 5;

SELECT * FROM TB_SHOP WHERE PRICE < 500;
