CREATE DATABASE DB_SCHOOL;

USE DB_SCHOOL;

CREATE TABLE TB_STUDENT(
    ID BIGINT AUTO_INCREMENT,
    NOME VARCHAR(255),
    SERIE VARCHAR(255),
    IDADE INT,
    NOTA INT,
    RA INT
    PRIMARY KEY (ID)
);

INSERT INTO TB_STUDENT (NOME, SERIE, IDADE, NOTA, RA) VALUES ("Nicolas", "8 ano", 13, 10, 857103);
INSERT INTO TB_STUDENT (NOME, SERIE, IDADE, NOTA, RA) VALUES ("Pedro", "8 ano", 13, 6, 283714);
INSERT INTO TB_STUDENT (NOME, SERIE, IDADE, NOTA, RA) VALUES ("Lucas", "8 ano", 13, 8, 615985);
INSERT INTO TB_STUDENT (NOME, SERIE, IDADE, NOTA, RA) VALUES ("João", "8 ano", 13, 4, 404957);
INSERT INTO TB_STUDENT (NOME, SERIE, IDADE, NOTA, RA) VALUES ("Gabriel", "8 ano", 13, 6, 131777);
INSERT INTO TB_STUDENT (NOME, SERIE, IDADE, NOTA, RA) VALUES ("Paulo", "8 ano", 13, 7, 289920);
INSERT INTO TB_STUDENT (NOME, SERIE, IDADE, NOTA, RA) VALUES ("Marcos", "8 ano", 13, 8, 778500);
INSERT INTO TB_STUDENT (NOME, SERIE, IDADE, NOTA, RA) VALUES ("Kayque", "8 ano", 13, 9, 939623);

SELECT * FROM TB_STUDENT;

SELECT * FROM TB_STUDENT WHERE NOTA > 7;

SELECT * FROM TB_STUDENT WHERE NOTA < 7;

uptade TB_STUDENT SET SERIE = "3 ANO DO ENSINO MEDIO" ID = 8;