CREATE DATABASE DB_SERVICO_RH;

USE DB_SERVICO_RH;

CREATE TABLE TB_FUNCIONARIOS(

ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
IDADE INT NOT NULL,
PRIMARY KEY (ID),
COLABORADOR_ID BIGINT,
FOREIGN KEY (COLABORADOR_ID) REFERENCES TB_CARGOS(ID)
);

CREATE TABLE TB_CARGOS(
ID BIGINT AUTO_INCREMENT,
CARGO VARCHAR (255) NOT NULL,
SALARIO DECIMAL NOT NULL,
PRIMARY KEY(ID)
);

SELECT * FROM TB_FUNCIONARIOS;
SELECT * FROM TB_CARGOS;

INSERT INTO TB_CARGOS (CARGO, SALARIO) VALUES ("Back end Jr" , 5000.00);
INSERT INTO TB_CARGOS (CARGO, SALARIO) VALUES ("Back end Jr" , 5000.00);

INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, COLABORADOR_ID) VALUES ("Nicolas", 22, 1);