CREATE DATABASE DB_PIZZARIA_LEGAL;

USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_CATEGORIA(
ID BIGINT AUTO_INCREMENT,
SALGADA BOOLEAN NOT NULL,
DOCE BOOLEAN NOT NULL,
PRIMARY KEY (ID)
);

INSERT INTO TB_CATEGORIA (SALGADA, DOCE) VALUES (TRUE, FALSE);
INSERT INTO TB_CATEGORIA (SALGADA, DOCE) VALUES (FALSE, TRUE);
INSERT INTO TB_CATEGORIA (SALGADA, DOCE) VALUES (TRUE, TRUE);
INSERT INTO TB_CATEGORIA (SALGADA, DOCE) VALUES (FALSE, TRUE);
INSERT INTO TB_CATEGORIA (SALGADA, DOCE) VALUES (TRUE, FALSE);



CREATE TABLE TB_PIZZA(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR (255) NOT NULL,
DESCRICAO VARCHAR (255) NOT NULL,
PREPARO VARCHAR (255) NOT NULL,
PRECO DECIMAL (8,2) NOT NULL,
CATEGORIA_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIA(ID)
);

INSERT INTO TB_PIZZA (NOME, DESCRICAO, PREPARO, PRECO, CATEGORIA_ID) VALUES ("Da esquina", "Feita com coisas da cozinha", "Feita em 30min, se nao dinheiro de volta", 35.00, 1);
INSERT INTO TB_PIZZA (NOME, DESCRICAO, PREPARO, PRECO, CATEGORIA_ID) VALUES ("Calapiri", "Feita com calabresa e catupiry", "Feita em 30min, se nao dinheiro de volta", 50.00, 1);
INSERT INTO TB_PIZZA (NOME, DESCRICAO, PREPARO, PRECO, CATEGORIA_ID) VALUES ("Nutella", "Feita com nutella", "Feita em 30min, se nao dinheiro de volta", 45.00, 2);
INSERT INTO TB_PIZZA (NOME, DESCRICAO, PREPARO, PRECO, CATEGORIA_ID) VALUES ("Calabresa com nutella", "Feita com calabresa e nutella meio a meio", "Feita em 30min, se nao dinheiro de volta", 50.00, 3);
INSERT INTO TB_PIZZA (NOME, DESCRICAO, PREPARO, PRECO, CATEGORIA_ID) VALUES ("Da esquina", "Feita com coisas da cozinha", "Feita em 30min, se nao dinheiro de volta", 29.00, 1);
INSERT INTO TB_PIZZA (NOME, DESCRICAO, PREPARO, PRECO, CATEGORIA_ID) VALUES ("Da esquina", "Feita com coisas da cozinha", "Feita em 30min, se nao dinheiro de volta", 35.00, 1);
INSERT INTO TB_PIZZA (NOME, DESCRICAO, PREPARO, PRECO, CATEGORIA_ID) VALUES ("Da esquina", "Feita com coisas da cozinha", "Feita em 30min, se nao dinheiro de volta", 70.00, 1);
INSERT INTO TB_PIZZA (NOME, DESCRICAO, PREPARO, PRECO, CATEGORIA_ID) VALUES ("Da esquina", "Feita com coisas da cozinha", "Feita em 30min, se nao dinheiro de volta", 100.00, 1);


SELECT * FROM TB_PIZZA;

SELECT TB_PIZZA.NOME, TB_PIZZA.DESCRICAO, TB_PIZZA.PREPARO, TB_PIZZA.PRECO, TB_CATEGORIA.SALGADA, TB_CATEGORIA.DOCE FROM TB_PIZZA INNER JOIN TB_CATEGORIA ON TB_CATEGORIA.ID = TB_PIZZA.CATEGORIA_ID WHERE PRECO > 45;

SELECT TB_PIZZA.NOME, TB_PIZZA.DESCRICAO, TB_PIZZA.PREPARO, TB_PIZZA.PRECO, TB_CATEGORIA.SALGADA, TB_CATEGORIA.DOCE FROM TB_PIZZA INNER JOIN TB_CATEGORIA ON TB_CATEGORIA.ID = TB_PIZZA.CATEGORIA_ID WHERE PRECO BETWEEN 50 AND 100;

SELECT * FROM TB_PIZZA WHERE NOME LIKE "%C%";

SELECT TB_PIZZA.NOME, TB_PIZZA.DESCRICAO, TB_PIZZA.PREPARO, TB_PIZZA.PRECO, TB_CATEGORIA.SALGADA, TB_CATEGORIA.DOCE FROM TB_PIZZA INNER JOIN TB_CATEGORIA ON TB_CATEGORIA.ID - TB_PIZZA.CATEGORIA_ID WHERE DOCE = '1';
