CREATE DATABASE DB_GENERATION_GAME_ONLINE;

USE DB_GENERATION_GAME_ONLINE;

CREATE TABLE TB_CLASSES(
ID BIGINT AUTO_INCREMENT,
ATAQUE INT,
DEFESA INT,
PRIMARY KEY (ID)
);

INSERT INTO TB_CLASSES (ATAQUE, DEFESA) VALUES (2000, 900);
INSERT INTO TB_CLASSES (ATAQUE, DEFESA) VALUES (3879, 2000);
INSERT INTO TB_CLASSES (ATAQUE, DEFESA) VALUES (1500, 1500);
INSERT INTO TB_CLASSES (ATAQUE, DEFESA) VALUES (1233, 2400);
INSERT INTO TB_CLASSES (ATAQUE, DEFESA) VALUES (4000, 2300);

CREATE TABLE TB_PERSONAGEM(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
MAGO BOOLEAN NOT NULL,
GUERREIRO BOOLEAN NOT NULL,
ARQUEIRO BOOLEAN NOT NULL,
CLASSE_ID BIGINT,
PRIMARY KEY(ID),
FOREIGN KEY (CLASSE_ID) REFERENCES TB_CLASSES(ID)
);

INSERT INTO TB_PERSONAGEM (NOME, MAGO, GUERREIRO, ARQUEIRO, CLASSE_ID) VALUES ("Nicolas", true, false, false, 1);
INSERT INTO TB_PERSONAGEM (NOME, MAGO, GUERREIRO, ARQUEIRO, CLASSE_ID) VALUES ("Pedro", false, true, false, 2);
INSERT INTO TB_PERSONAGEM (NOME, MAGO, GUERREIRO, ARQUEIRO, CLASSE_ID) VALUES ("Nicole", true, false, false, 1);
INSERT INTO TB_PERSONAGEM (NOME, MAGO, GUERREIRO, ARQUEIRO, CLASSE_ID) VALUES ("Lucas", false, false, true, 3);
INSERT INTO TB_PERSONAGEM (NOME, MAGO, GUERREIRO, ARQUEIRO, CLASSE_ID) VALUES ("Carlos", true, false, false, 5);
INSERT INTO TB_PERSONAGEM (NOME, MAGO, GUERREIRO, ARQUEIRO, CLASSE_ID) VALUES ("Gabriel", true, false, false, 2);
INSERT INTO TB_PERSONAGEM (NOME, MAGO, GUERREIRO, ARQUEIRO, CLASSE_ID) VALUES ("Cleber", false, true, false, 3);
INSERT INTO TB_PERSONAGEM (NOME, MAGO, GUERREIRO, ARQUEIRO, CLASSE_ID) VALUES ("Fernanda", true, false, false, 1);

SELECT TB_PERSONAGEM.NOME, TB_PERSONAGEM.MAGO, TB_PERSONAGEM.GUERREIRO, TB_PERSONAGEM.ARQUEIRO, TB_CLASSES.ATAQUE, TB_CLASSES.DEFESA FROM TB_PERSONAGEM INNER JOIN TB_CLASSES ON TB_CLASSES.ID = TB_PERSONAGEM.CLASSE_ID WHERE ATAQUE > 2000;

SELECT TB_PERSONAGEM.NOME, TB_PERSONAGEM.MAGO, TB_PERSONAGEM.GUERREIRO, TB_PERSONAGEM.ARQUEIRO, TB_CLASSES.ATAQUE, TB_CLASSES.DEFESA FROM TB_PERSONAGEM INNER JOIN TB_CLASSES ON TB_CLASSES.ID = TB_PERSONAGEM.CLASSE_ID WHERE DEFESA BETWEEN 1000 AND 2000;

SELECT * FROM TB_PERSONAGEM WHERE NOME LIKE "%C%";

SELECT TB_PERSONAGEM.NOME, TB_PERSONAGEM.MAGO, TB_PERSONAGEM.GUERREIRO, TB_PERSONAGEM.ARQUEIRO, TB_CLASSES.ATAQUE, TB_CLASSES.DEFESA FROM TB_PERSONAGEM INNER JOIN TB_CLASSES ON TB_CLASSES.ID = TB_PERSONAGEM.CLASSE_ID WHERE ARQUEIRO = 1;