CREATE DATABASE DB_RH;

USE DB_RH;

CREATE TABLE TB_FUNCIONARIOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
IDADE INT,
FUNCAO VARCHAR(255),
SALARIO DOUBLE,
QUALIDADES VARCHAR(255),
PRIMARY KEY (ID)
);

INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, FUNCAO, SALARIO, QUALIDADES) VALUES ("Nicolas", 18, "Desenvolvedor Back-end Jr", 2500, "Atencioso");
INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, FUNCAO, SALARIO, QUALIDADES) VALUES ("Lucas", 34, "Desenvolvedor Full Stack", 2679, "Atencioso");
INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, FUNCAO, SALARIO, QUALIDADES) VALUES ("Pedro", 23, "Desenvolvedor Front End Jr", 1700, "Atencioso");
INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, FUNCAO, SALARIO, QUALIDADES) VALUES ("Amanda", 26, "Desenvolvedor Java Pleno", 3588, "Atencioso");
INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, FUNCAO, SALARIO, QUALIDADES) VALUES ("Joao", 19, "UIX Jr", 1500, "Atencioso");

SELECT * FROM TB_FUNCIONARIOS;

update tb_funcionarios set salario = 1800.00 where id = 1;

SELECT * from TB_FUNCIONARIOS WHERE SALARIO > 2000;
SELECT * from TB_FUNCIONARIOS WHERE SALARIO < 2000;

update tb_funcionarios set salario = 3500.00 where id = 1;